//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssessmentResultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssessmentResultType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="satisfaction"/>
 *     &lt;enumeration value="violation"/>
 *     &lt;enumeration value="notAssessed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssessmentResultType")
@XmlEnum
public enum AssessmentResultType {

    @XmlEnumValue("satisfaction")
    SATISFACTION("satisfaction"),
    @XmlEnumValue("violation")
    VIOLATION("violation"),
    @XmlEnumValue("notAssessed")
    NOT_ASSESSED("notAssessed");
    private final String value;

    AssessmentResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssessmentResultType fromValue(String v) {
        for (AssessmentResultType c: AssessmentResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
