//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for GuatanteedStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GuatanteedStateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.slaatsoi.org/eventschema}GuaranteedType">
 *       &lt;sequence>
 *         &lt;element name="QoSName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GuatanteedStateType", propOrder = {
    "qoSName",
    "qoSValue"
})
public class GuatanteedStateType
    extends GuaranteedType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "QoSName", required = true)
    protected String qoSName;
    @XmlElement(name = "QoSValue", required = true)
    protected String qoSValue;

    /**
     * Gets the value of the qoSName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSName() {
        return qoSName;
    }

    /**
     * Sets the value of the qoSName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSName(String value) {
        this.qoSName = value;
    }

    /**
     * Gets the value of the qoSValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSValue() {
        return qoSValue;
    }

    /**
     * Sets the value of the qoSValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSValue(String value) {
        this.qoSValue = value;
    }

}
