//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyDescriptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropertyDescriptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Functional"/>
 *     &lt;enumeration value="Non-Functional"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PropertyDescriptionType")
@XmlEnum
public enum PropertyDescriptionType {

    @XmlEnumValue("Functional")
    FUNCTIONAL("Functional"),
    @XmlEnumValue("Non-Functional")
    NON_FUNCTIONAL("Non-Functional");
    private final String value;

    PropertyDescriptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropertyDescriptionType fromValue(String v) {
        for (PropertyDescriptionType c: PropertyDescriptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
