//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for EventSource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SwServiceLayerSource" type="{http://www.slaatsoi.org/eventschema}ServiceSourceType"/>
 *         &lt;element name="InfrastructureLayer" type="{http://www.slaatsoi.org/eventschema}InfrastructureLayerSource"/>
 *         &lt;element name="Other" type="{http://www.slaatsoi.org/eventschema}OtherSource"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSource", propOrder = {
    "swServiceLayerSource",
    "infrastructureLayer",
    "other"
})
public class EventSource
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SwServiceLayerSource")
    protected ServiceSourceType swServiceLayerSource;
    @XmlElement(name = "InfrastructureLayer")
    protected InfrastructureLayerSource infrastructureLayer;
    @XmlElement(name = "Other")
    protected OtherSource other;

    /**
     * Gets the value of the swServiceLayerSource property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceSourceType }
     *     
     */
    public ServiceSourceType getSwServiceLayerSource() {
        return swServiceLayerSource;
    }

    /**
     * Sets the value of the swServiceLayerSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceSourceType }
     *     
     */
    public void setSwServiceLayerSource(ServiceSourceType value) {
        this.swServiceLayerSource = value;
    }

    /**
     * Gets the value of the infrastructureLayer property.
     * 
     * @return
     *     possible object is
     *     {@link InfrastructureLayerSource }
     *     
     */
    public InfrastructureLayerSource getInfrastructureLayer() {
        return infrastructureLayer;
    }

    /**
     * Sets the value of the infrastructureLayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfrastructureLayerSource }
     *     
     */
    public void setInfrastructureLayer(InfrastructureLayerSource value) {
        this.infrastructureLayer = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link OtherSource }
     *     
     */
    public OtherSource getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherSource }
     *     
     */
    public void setOther(OtherSource value) {
        this.other = value;
    }

}
