//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SecurityPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GuaranteedState" type="{http://www.slaatsoi.org/eventschema}GuatanteedStateType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="securityPropertyID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cmInstanceID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="assessmentResult" type="{http://www.slaatsoi.org/eventschema}AssessmentResultType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityPropertyType", propOrder = {
    "guaranteedState"
})
public class SecurityPropertyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "GuaranteedState", required = true)
    protected List<GuatanteedStateType> guaranteedState;
    @XmlAttribute(required = true)
    protected String securityPropertyID;
    @XmlAttribute(required = true)
    protected String cmInstanceID;
    @XmlAttribute
    protected AssessmentResultType assessmentResult;

    /**
     * Gets the value of the guaranteedState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guaranteedState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuaranteedState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GuatanteedStateType }
     * 
     * 
     */
    public List<GuatanteedStateType> getGuaranteedState() {
        if (guaranteedState == null) {
            guaranteedState = new ArrayList<GuatanteedStateType>();
        }
        return this.guaranteedState;
    }

    /**
     * Gets the value of the securityPropertyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPropertyID() {
        return securityPropertyID;
    }

    /**
     * Sets the value of the securityPropertyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPropertyID(String value) {
        this.securityPropertyID = value;
    }

    /**
     * Gets the value of the cmInstanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmInstanceID() {
        return cmInstanceID;
    }

    /**
     * Sets the value of the cmInstanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmInstanceID(String value) {
        this.cmInstanceID = value;
    }

    /**
     * Gets the value of the assessmentResult property.
     * 
     * @return
     *     possible object is
     *     {@link AssessmentResultType }
     *     
     */
    public AssessmentResultType getAssessmentResult() {
        return assessmentResult;
    }

    /**
     * Sets the value of the assessmentResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessmentResultType }
     *     
     */
    public void setAssessmentResult(AssessmentResultType value) {
        this.assessmentResult = value;
    }

}
