//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for SimpleArgument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleArgument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArgType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DirectionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleArgument", propOrder = {
    "argName",
    "argType",
    "direction",
    "value"
})
public class SimpleArgument
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ArgName", required = true)
    protected String argName;
    @XmlElement(name = "ArgType", required = true)
    protected String argType;
    @XmlElement(name = "Direction", required = true)
    protected String direction;
    @XmlElement(name = "Value", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected Object value;

    /**
     * Gets the value of the argName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgName() {
        return argName;
    }

    /**
     * Sets the value of the argName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgName(String value) {
        this.argName = value;
    }

    /**
     * Gets the value of the argType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgType() {
        return argType;
    }

    /**
     * Sets the value of the argType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgType(String value) {
        this.argType = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setValue(Object value) {
        this.value = value;
    }

}
