//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventInstance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EventID" type="{http://www.slaatsoi.org/eventschema}EventIdType"/>
 *         &lt;element name="EventContext" type="{http://www.slaatsoi.org/eventschema}EventContextType"/>
 *         &lt;element name="EventPayload" type="{http://www.slaatsoi.org/eventschema}EventPayloadType"/>
 *         &lt;element name="EventMetadata" type="{http://www.slaatsoi.org/eventschema}EventMetaDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Event")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventInstance", propOrder = {
    "eventID",
    "eventContext",
    "eventPayload",
    "eventMetadata"
})
public class EventInstance
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EventID", required = true)
    protected EventIdType eventID;
    @XmlElement(name = "EventContext", required = true)
    protected EventContextType eventContext;
    @XmlElement(name = "EventPayload", required = true)
    protected EventPayloadType eventPayload;
    @XmlElement(name = "EventMetadata")
    protected List<EventMetaDataType> eventMetadata;

    /**
     * Gets the value of the eventID property.
     * 
     * @return
     *     possible object is
     *     {@link EventIdType }
     *     
     */
    public EventIdType getEventID() {
        return eventID;
    }

    /**
     * Sets the value of the eventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventIdType }
     *     
     */
    public void setEventID(EventIdType value) {
        this.eventID = value;
    }

    /**
     * Gets the value of the eventContext property.
     * 
     * @return
     *     possible object is
     *     {@link EventContextType }
     *     
     */
    public EventContextType getEventContext() {
        return eventContext;
    }

    /**
     * Sets the value of the eventContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventContextType }
     *     
     */
    public void setEventContext(EventContextType value) {
        this.eventContext = value;
    }

    /**
     * Gets the value of the eventPayload property.
     * 
     * @return
     *     possible object is
     *     {@link EventPayloadType }
     *     
     */
    public EventPayloadType getEventPayload() {
        return eventPayload;
    }

    /**
     * Sets the value of the eventPayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPayloadType }
     *     
     */
    public void setEventPayload(EventPayloadType value) {
        this.eventPayload = value;
    }

    /**
     * Gets the value of the eventMetadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventMetadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventMetaDataType }
     * 
     * 
     */
    public List<EventMetaDataType> getEventMetadata() {
        if (eventMetadata == null) {
            eventMetadata = new ArrayList<EventMetaDataType>();
        }
        return this.eventMetadata;
    }

}
