//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfrastructureMonitoringEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfrastructureMonitoringEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infrastructureId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="infrastructureEventType" type="{http://www.slaatsoi.org/eventschema}InfrastructureEventType"/>
 *         &lt;element name="infrastructureProperties" type="{http://www.slaatsoi.org/eventschema}InfrastructurePropertiesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfrastructureMonitoringEventType", propOrder = {
    "infrastructureId",
    "resourceId",
    "infrastructureEventType",
    "infrastructureProperties"
})
public class InfrastructureMonitoringEventType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String infrastructureId;
    @XmlElement(required = true)
    protected String resourceId;
    @XmlElement(required = true)
    protected InfrastructureEventType infrastructureEventType;
    @XmlElement(required = true)
    protected InfrastructurePropertiesType infrastructureProperties;

    /**
     * Gets the value of the infrastructureId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfrastructureId() {
        return infrastructureId;
    }

    /**
     * Sets the value of the infrastructureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfrastructureId(String value) {
        this.infrastructureId = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceId(String value) {
        this.resourceId = value;
    }

    /**
     * Gets the value of the infrastructureEventType property.
     * 
     * @return
     *     possible object is
     *     {@link InfrastructureEventType }
     *     
     */
    public InfrastructureEventType getInfrastructureEventType() {
        return infrastructureEventType;
    }

    /**
     * Sets the value of the infrastructureEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfrastructureEventType }
     *     
     */
    public void setInfrastructureEventType(InfrastructureEventType value) {
        this.infrastructureEventType = value;
    }

    /**
     * Gets the value of the infrastructureProperties property.
     * 
     * @return
     *     possible object is
     *     {@link InfrastructurePropertiesType }
     *     
     */
    public InfrastructurePropertiesType getInfrastructureProperties() {
        return infrastructureProperties;
    }

    /**
     * Sets the value of the infrastructureProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfrastructurePropertiesType }
     *     
     */
    public void setInfrastructureProperties(InfrastructurePropertiesType value) {
        this.infrastructureProperties = value;
    }

}
