//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitoringResultEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MonitoringResultEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SecurityPropertyInfo" type="{http://www.slaatsoi.org/eventschema}SecurityPropertyType"/>
 *         &lt;element name="MonitoringInfo" type="{http://www.slaatsoi.org/eventschema}MonitoringInfoType"/>
 *         &lt;element name="ExtraProperties" type="{http://www.slaatsoi.org/eventschema}PropertiesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoringResultEventType", propOrder = {
    "securityPropertyInfo",
    "monitoringInfo",
    "extraProperties"
})
public class MonitoringResultEventType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SecurityPropertyInfo", required = true)
    protected SecurityPropertyType securityPropertyInfo;
    @XmlElement(name = "MonitoringInfo", required = true)
    protected MonitoringInfoType monitoringInfo;
    @XmlElement(name = "ExtraProperties", required = true)
    protected PropertiesType extraProperties;

    /**
     * Gets the value of the securityPropertyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityPropertyType }
     *     
     */
    public SecurityPropertyType getSecurityPropertyInfo() {
        return securityPropertyInfo;
    }

    /**
     * Sets the value of the securityPropertyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityPropertyType }
     *     
     */
    public void setSecurityPropertyInfo(SecurityPropertyType value) {
        this.securityPropertyInfo = value;
    }

    /**
     * Gets the value of the monitoringInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringInfoType }
     *     
     */
    public MonitoringInfoType getMonitoringInfo() {
        return monitoringInfo;
    }

    /**
     * Sets the value of the monitoringInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringInfoType }
     *     
     */
    public void setMonitoringInfo(MonitoringInfoType value) {
        this.monitoringInfo = value;
    }

    /**
     * Gets the value of the extraProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getExtraProperties() {
        return extraProperties;
    }

    /**
     * Sets the value of the extraProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setExtraProperties(PropertiesType value) {
        this.extraProperties = value;
    }

}
