//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.24 at 12:58:26 PM BST 
//


package org.slaatsoi.eventschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.slaatsoi.eventschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Event_QNAME = new QName("http://www.slaatsoi.org/eventschema", "Event");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.slaatsoi.eventschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventInstance }
     * 
     */
    public EventInstance createEventInstance() {
        return new EventInstance();
    }

    /**
     * Create an instance of {@link EventTime }
     * 
     */
    public EventTime createEventTime() {
        return new EventTime();
    }

    /**
     * Create an instance of {@link PredictionInfoType }
     * 
     */
    public PredictionInfoType createPredictionInfoType() {
        return new PredictionInfoType();
    }

    /**
     * Create an instance of {@link ArgumentList }
     * 
     */
    public ArgumentList createArgumentList() {
        return new ArgumentList();
    }

    /**
     * Create an instance of {@link EventSource }
     * 
     */
    public EventSource createEventSource() {
        return new EventSource();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link PredictionResultEventType }
     * 
     */
    public PredictionResultEventType createPredictionResultEventType() {
        return new PredictionResultEventType();
    }

    /**
     * Create an instance of {@link EventMetaDataType }
     * 
     */
    public EventMetaDataType createEventMetaDataType() {
        return new EventMetaDataType();
    }

    /**
     * Create an instance of {@link SecurityPropertyType }
     * 
     */
    public SecurityPropertyType createSecurityPropertyType() {
        return new SecurityPropertyType();
    }

    /**
     * Create an instance of {@link InfrastructureLayerSource }
     * 
     */
    public InfrastructureLayerSource createInfrastructureLayerSource() {
        return new InfrastructureLayerSource();
    }

    /**
     * Create an instance of {@link ServiceSourceType }
     * 
     */
    public ServiceSourceType createServiceSourceType() {
        return new ServiceSourceType();
    }

    /**
     * Create an instance of {@link ArgumentType }
     * 
     */
    public ArgumentType createArgumentType() {
        return new ArgumentType();
    }

    /**
     * Create an instance of {@link EventContextType }
     * 
     */
    public EventContextType createEventContextType() {
        return new EventContextType();
    }

    /**
     * Create an instance of {@link SimpleArgument }
     * 
     */
    public SimpleArgument createSimpleArgument() {
        return new SimpleArgument();
    }

    /**
     * Create an instance of {@link EventIdType }
     * 
     */
    public EventIdType createEventIdType() {
        return new EventIdType();
    }

    /**
     * Create an instance of {@link InfrastructurePropertiesType }
     * 
     */
    public InfrastructurePropertiesType createInfrastructurePropertiesType() {
        return new InfrastructurePropertiesType();
    }

    /**
     * Create an instance of {@link GuatanteedStateType }
     * 
     */
    public GuatanteedStateType createGuatanteedStateType() {
        return new GuatanteedStateType();
    }

    /**
     * Create an instance of {@link InfrastructureMonitoringEventType }
     * 
     */
    public InfrastructureMonitoringEventType createInfrastructureMonitoringEventType() {
        return new InfrastructureMonitoringEventType();
    }

    /**
     * Create an instance of {@link EventPayloadType }
     * 
     */
    public EventPayloadType createEventPayloadType() {
        return new EventPayloadType();
    }

    /**
     * Create an instance of {@link MonitoringResultEventType }
     * 
     */
    public MonitoringResultEventType createMonitoringResultEventType() {
        return new MonitoringResultEventType();
    }

    /**
     * Create an instance of {@link StructArgument }
     * 
     */
    public StructArgument createStructArgument() {
        return new StructArgument();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link EventNotifier }
     * 
     */
    public EventNotifier createEventNotifier() {
        return new EventNotifier();
    }

    /**
     * Create an instance of {@link PropertiesType.Property }
     * 
     */
    public PropertiesType.Property createPropertiesTypeProperty() {
        return new PropertiesType.Property();
    }

    /**
     * Create an instance of {@link GuaranteedType }
     * 
     */
    public GuaranteedType createGuaranteedType() {
        return new GuaranteedType();
    }

    /**
     * Create an instance of {@link OtherSource }
     * 
     */
    public OtherSource createOtherSource() {
        return new OtherSource();
    }

    /**
     * Create an instance of {@link MonitoringInfoType }
     * 
     */
    public MonitoringInfoType createMonitoringInfoType() {
        return new MonitoringInfoType();
    }

    /**
     * Create an instance of {@link InteractionEventType }
     * 
     */
    public InteractionEventType createInteractionEventType() {
        return new InteractionEventType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventInstance }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.slaatsoi.org/eventschema", name = "Event")
    public JAXBElement<EventInstance> createEvent(EventInstance value) {
        return new JAXBElement<EventInstance>(_Event_QNAME, EventInstance.class, null, value);
    }

}
